name: "Activity issue"
description: >
  Create an issue for a Activity.
  An activity is composed from one or more Task issues.
  An activity can optionally be part of an Umbrella.
labels: ["Activity"]
projects: ["makortel/2"]
body:
- type: markdown
  attributes: 
    value: |
      After creating the Activity issue
      * Create Tasks as sub-issues
        * Or assign also `Task` label for this issue if the Activity contains only one Task
      * If you start to work on the Activity immediately, expand the "Framework Activities" project on the pane on the right, and
        * Set `Status` to `In progress`
        * Assign `Quarter` as current quarter
        * Set `Began` to the date you started working on the Activity
- type: textarea
  attributes:
    label: "Description"
    description: "Description of the Activity (can be empty)"
    placeholder: >
      Write here something about the activity if it is not clear from the title.
      If there are relevant issue(s) elsewhere (e.g. in cms-sw/cmssw), link them here.
