name: "Task issue"
description: "Create a Task issue"
labels: ["Task"]
projects: ["makortel/2"]
body:
- type: textarea
  attributes:
    label: "Description"
    description: "Optional description of the task"
    placeholder: "E.g. a link to a PR"
